---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio-root-credentials-sealedsecret.yaml
- helmrepository.yaml
- helmchart.yaml
- helmrelease.yaml
- serverstransport.yaml
- ingressroute.yaml
- minio-console-tls.yaml
