---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stackgres
  namespace: stackgres
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: stackgres
    namespace: stackgres
  values:
    restapi:
      service:
        annotations:
          traefik.ingress.kubernetes.io/service.serverstransport: "stackgres-stackgres@kubernetescrd"
