---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-admin-credentials
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: opensearch-admin-credentials
  data:
    - secretKey: cookie
      remoteRef:
        key: opensearch/admin-credentials
        property: cookie
    - secretKey: password
      remoteRef:
        key: opensearch/admin-credentials
        property: password
    - secretKey: username
      remoteRef:
        key: opensearch/admin-credentials
        property: username
