---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections-import
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    connections.yaml: AgCngIGlNK1qzWH/DwDiE7Z7WVLPniIIUESihG+hZtEKKyspB9HJJlUV2DaSAkQd/ZTRjjK4RO+kDY9BQ7Myw8ck+IMpImkVa3PMLrla03DIvHt9zEwwsXvbUpzMb0GRYZPsRK9+niMDYS26sOOv1X+gsf3K9wwCAwwEshxmlKSfb041XLqX6l+ExylyAXFoH6ZBtPPQy472ePTOxBD+tRKiUFegWyb6TAhcGPT4CFBcFzVni5R0wwXUGxWcW2kcFVqdyMWbBlQQ43wVUj8tErY7BwAI/cRp5UWVhEpIQGf3SFdMkrDzquyLZAxqLZ2omsduXOK3r954GVp9n+aJaX2P81dzlwx3D6llSRNT+bPu38pxkKVkRluu2HdyFBEnjkgs0ZvOwCRYXOPNwlu8yq6jSU67okxTJZ2uWxzt2xzk9zbRr/tOli3qbS8uuWfgIBctP/ACW5FWk19es1of4BcRkv5qzh+e/RPP+7YpK1zSodUVvN7DNfvzO2NkOs17Z0lgyiaAdJLpkd7bKalHpNjtGOkraozj4fbzKI96yBmoBu0CbQrtVOiqSx0MYcIZ62NbaYpXlChfETpBMKxDe2F7CJy5xnUveh6dWhas0gqjzuqzTDHvWM62cz0zMmxsBDgcdPSv9QiOLCmOJjusrI9Xj/kl/uAb+k/G5ENsnEeI4GC9pzfc4s6/PiNDU4W0md8PMRr8uyyEIml/fACgfyWT5TanvRvd1SJqgxSdjAMPTryuVxM4jylY6uCxfhy3KZ8AEnl8hqrXoQ6872WKvc6VEUPwoeINPW3nGKs1i04V5zmyT93NzbHVlM2ekiKCWv/Fwx3ps9jCq/vzfgXiCW/EazVuN7WHQA0ry+emt9SaxETcy4+650OOmRLLQF+9/nLMDJrKAL7B8jcsCo56O3a84lRAp2fIO5wT1K2kMUKZHIpXbOGoiwTL4+STuWvJy3Fp
  template:
    metadata:
      name: airflow-connections-import
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
