---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-opensearch-connection
  namespace: airflow
spec:
  encryptedData:
    connection: AgB0oMD5vYUaGIcsbliE52eVmQi6KPi2CQ6/R997wUtXCZSVqG546e+kJqXKadUPCyWfL/423u4EB9/o5D6q/+WjggV8c2i7sles+ebYQ4RpK9yb+RFzui8SRH4+2TWmED3G6XsNQ+kdW6G9r2Na/w9YXVkPNnteGI3sNEqTIwo+P4wMGiiyc6hDeiU7IhqIW1ono0QzgDS5uDTqLMRTbHTEEcyP4HbvgqkHiCmnw6dvYk3bLnyZ1Tldxb5ptSyeZcNoZqLgxPgawUaHoq28yt5vwICqyuk7sWs2oDcAl9ndwAeWyGH/OobrIV7OqEUv9WQY/LcxK3y/F3vkQ8wFRuWMlSdPrDBXfdb4Pgp0fjRDVqeLFLiqHXbU5+dNqLjVyHNnxlnHJJCdP7F7u+T+JxBfdT7cHTsdJuZHEcKER8z+0zuStnHYwJRysOxXQtnqei/FzorQiiw2u7Dj4sigd8xlHYMfRjCp8/2uaHC2d1lNTVr+vd0WAAJ32GIznRUvXo3Icqf/5BhRboQPESd1QCUWfYQiwrF5ZNod9F4SYepXUGZ+usgVbGcCOPKXTBTXj3wKieZObTvq+1reusnxIm/QwASXNYQRfiWN4JVadZjlEfCqIF09NruOVye3cg5tkiKxwWGcVo8iZilKKVMXHIWUpwNPUrnjvYJ/xmpThJAI0F5JGCsc+J29w+xUlbA+8kf8eBV3AT7jWtkmmrEgNTajzGDVA8/nymyjSbz4O80LitUVVcRbt8u1ZJbgKRk6tg3i+e87HgVCA618RdOW  template:
    metadata:
      name: airflow-opensearch-connection
      namespace: airflow
