---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: kserve-api-keys
  namespace: kserve
spec:
  encryptedData:
    litellm: AgCKD0Pi+EF5NJ6dwUbMJwqL2CG3wN8NR/mi3d/Tlwf6TxHNWz3MxkuxLVlq81hWDROtMGqrk8rcnQ9STrD5LCzoWmYYE6YCb8BZA/BnrwER8skNPJNIrv+wR4/EZOpIS4/dxHQB0zxZF7Vheg8d79SUNxwcpp3vBw2Q59Be865qB4G6h3eY6xJsyXneWeCvYy2ZKdzLQvJdopae3GRbZO3NJOvkEIvm1ZDdkW0rporoLOT9VplfD4haL+2xky0avo/V09SlK+kP31VDxjkRZ6uZJdJV1p5IU6gI5jXJbVkycorF7VrchGSKOXps6sH/YZ3+9OipI/5v4V2ILRSGeWprQisxWOWb6QuNaxEcHEAklo6XEe5mJwTvqP2UmwdjSqCqe+rMjSKNzdaEEcputMG/5dUWW8ITZWAoQIFEL15nlxHPgKzPBP0wb9EMplNGzLj2Anr8+7Ps/bZQd/a5OSuLgxZrd2HH0MnuhT0GP8okLjBl8t2+rAWiXeXiai/SC7+mGthPX6FAp/vqXsAVlDq2f8zeqaK7IEH7LfBkkSlQFQbqMZXcsbwokAEIVUR83ulhRIU7eoEVgczz1LDvE2zw4YB3rBOOU++lvg7dQCWVrsQBMDW+ZqR+a1QTYRpzNiinsIBtOSxBObEq0p++sxlnlMF+dEYIlkjSFiGEDnLAB0uxi3dy0cw5PL+TRmqFXA3N5E3GCQOAHIHB6MyZ2WKMBKH/FVGbwLhiH1oezHsCYWrlbqxynMh1d2yyA6ViUIw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: kserve-api-keys
      namespace: kserve
