---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: kserve-api-keys
  namespace: kserve
spec:
  encryptedData:
    shubham: AgCWxf9YhbG9Mf0uslQJPORXmpDooKf2eXMM2M6WCT3lI0swYJPssjz+OkrZ5wbUwuqQWoJUxyyBOT3NZ9wdj5lqoiWMff6z89LX6XI4pvvuwKgBhfRhz6PNb8KbpUiOO5akCys0J3fYdySzjp+JnsGQH7Pi9toa83U0vHfHzzpNa+o8KemCbP4N2/XojC7XnqNTAP9drRP9qGN/CKZLKE8zszOKo+/gxLHmEqA4IQoxAXQQtN15Hsm179TJ4FDG6uDz/hdkhoEGA20tSmToUiGIA2+hoYdU7SKbz4yROBMwucMDr8xOEW2ju89/rICLwRt+TaPhLgaCqUTgJ5dnQdIXQP+f5TsG1qsoNqH0vFfq29/ETww8Ul3Nh3HQTRz50VbOtJbHvZxncfiyqTrJ76K7Kqa1IuiLbs+w+WcK0fA1zoaRdiDslSYGmTSXMIGM8BLfsFuJhYxz0KVxil+YktbyEFFSFV3vU8UI71wgTuJlU4Ls7kIhr0eGGXC/MoRkpBpBKCKSA83fU53e/33RJAJjONETQCpMrpIdQMSKyIkZpBednFrrSiojUTcyCMHnYpta9IWwH4vdXI8J+Y2jT0g15ay7fpkl+UZEal5NtZleP9ONOBFec0GjQSUqQRs8tOJoSQ43rNk3EaYicP0vnyfkHKM5INt/2Qi3BRqiuKlfYd8D5u3nxAJmKMjSZcJ8rOMlxj/5yzYgBVWIgHWmZLfTb0xV7oPwG6c9UIh7cgLQA0HpbVvzMSz3PaoOzZXmPT/MgwM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: kserve-api-keys
      namespace: kserve
