---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: dex
    namespace: dex
  values:
    config:
      issuer: https://dex.k8s.shubhamtatvamasi.com
      storage:
        type: memory
      web:
        http: 0.0.0.0:5556
      oauth2:
        skipApprovalScreen: true
      enablePasswordDB: true
      staticPasswords:
        - email: "admin@shubhamtatvamasi.com"
          hash: "$2y$10$SCGWSS0JvcJYgmbKLltITOnWH.1rc2yHiJOcQgqpDphSZkRrlmoza"
          username: "admin"
          userID: "1"
      staticClients:
        - id: flux-web-ui
          redirectURIs:
            - "https://flux.k8s.shubhamtatvamasi.com/oauth2/callback"
          name: Flux Web UI
          secret: "flux-dex-client-secret"
        - id: traefik-dashboard
          redirectURIs:
            - "https://traefik.k8s.shubhamtatvamasi.com/oauth2/callback"
          name: Traefik Dashboard
          secret: "traefik-dex-client-secret"
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: dex.k8s.shubhamtatvamasi.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dex-tls
          hosts:
            - dex.k8s.shubhamtatvamasi.com
