---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: airflow
  namespace: ${namespace}
spec:
  interval: 10m
  # url: https://airflow.apache.org
  url: https://shubhamtatvamasi.com/airflow-chart/
