---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 10m
  url: oci://ghcr.io/bank-vaults/helm-charts/vault-operator
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "1.24.0"
