---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      version: "28.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus
  values:
    server:
      image:
        tag: ""
