---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart: prometheus
  version: "28.15.x"
  sourceRef:
    name: prometheus
    kind: HelmRepository
