---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: prometheus
    namespace: prometheus
  values:
    server:
      image:
        tag: "v3.10.0"
