---
# Envoy Gateway CRDs only; the Gateway API and GIE CRDs come from the gateway-api kustomization
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: envoy-gateway-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway-crds
    namespace: envoy-gateway-system
  values:
    crds:
      gatewayAPI:
        enabled: false
      envoyGateway:
        enabled: true
