---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AIRFLOW_CONN_MY_POSTGRES: AgARL8gw87+RV4WXOPdcJ6Bag+0Q4YKkPlgsKy3EfRk+Ako2Oe7MOa8ANnQctHfyR56UB4/wek5YefRKXQSF7DvyjrlHjl/OAfL0eS2SzQCIB2VYvhMNS3In7UO3EpIAIj9vtRAVlQaNZBeOLT+jsFDSf8mx0vC7IqqO2oqOKjvk8RDQIP93Dm8jFbyQw9u0ybhNtG7Wbo/G4htzZYABnXrtOefL6Buv7cQ8j+SlUuT8bDx7Y6eZDZfL7fcjOqeiLLwvowwKqgR9fu1qmR+Bpg62DeoWRaykYC6reyoGXRYlWndhMWYYXbCVOrjICbjvPGk+2G8XBLi0uqrWvVNH0NI3Jim2KCHNm5mL6DUznF8eH1FkjN4rhYrd0Pb9bpw3hf92P/9fda90qDr43f4qsr9xgls4kJGvAkYCLx50eWpVHcQiNTh8L1U2CxOS62YzC6cnjhGCAKTmqYezsgw0iW9RSg2Yfh6SlDubA12rmGChtbj8HNtNl4+eEfXfeP4ia+SUm4i/pe4tQNwvJ6sRxAvYYMypMEj5pvz3fmoeTckgsX2xeLCn5/sI2/04A6pIgK9Yh9kqRca9KaiGphCj4Haw3BH07cLrOOZlMLTkQ928zrJS2E267mjfyALGyDPl8FfFohIZE93nLGFrnLjekcdH5uBMbZRQIgeJxQBQ2bsj/RBnMe3VrLkMOD4RfaLo3D539DixL48Xh1Xz4472NwYHKtZAK+YNkvQ1pOpk+pkURhHgTtEkhtkQNLRwV+QKnZ2wYNvyHG9782yX4+toVvyC75LFdpRGC3g=
  template:
    metadata:
      name: airflow-connections
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
