---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AIRFLOW_CONN_MY_HARBOR: AgBH/k68zAV9e9zHCowDL95MrY0QPdaHXxAL4fQlf4hVA42ABhVBlLzdPfhCDUJ76UyOnSmxcUoNx//Y7FU26X/fWkvEcIGC4DnQwZ8gd63wKBshEED8kAnqbkvCNAUgj5CmFuh/tifxv7St3GHGbepvI9HohkdVEI/x6UDbHERVfvqhyJluhUSGj7s+h8GE5pCrJngG37JRqjQD/fqlDIKykX0ephbCYdjq7G+3u4nPImhZ/KFNQ6Bat/B+eY65Ot8VRAaN5Z9NE3Sdjy+1hH0E5f2mpcAVMLJL/aqauwtoT3lFIqm+kbvamyibdKY067hOeZoH40IdSKsMgpriHAkSj3F2e5u+5ufCDA/uZ9yhyP8suNqdi5D53KRVDhTxbjOqfxOWBI0OHypS5QkfFDwUwZT2NLmtLKM447Oe7NwsaP3OqTvXKNzUH+SkN+fRvC3m+FwIhkzHIWCFVxHrr+//7e4h2BMOiOrP/4mfFMIWYqAu+iNSQ1bmZjWHqLPjjAdCFwkzNx1JzrPON5hexaU3j2vY9QuGMOar/JMosabnDJ1vvq5FqK1xDA+evj6WzlxhGRmeav2FCihpZ/oavXo7z/gaWm/dbpVu8Bg8uXCI0X9o7/wPlytSFIsYfzXbzHYGyKqE8TX4seNejUyH/BuEzlEieNvm2oMBOzxq53gK8RNTszD3JvAFwsUAfiMrA5ZLF2QdLv0LF0LsXFLiR0ld3iQ8tWV8Y2HCCkLOySDJ79OFvQRE6y/x8DtNOrvSQ6zYRtg=
    AIRFLOW_CONN_MY_POSTGRES: AgBo0DNH1rWYDKZTHNcecSkdRb7BCgMKz1YoTY357Fi4MQtUfMWrx8Ojc0iCSP2glG7maA3IyOHe3cZT+XYRkAHpZ8gWh8U2SobG/ZaKni8mEpKA3ad1BVgEZOfUiH4fGAutxLjbHXV51iMTvMMwBcn6tLsMM9hcYc2skzVCobVSVHnrqAB2eYsyyzWahWaqolivbAoh8WXvJj0zLtvJjFYP2gMZFB1jgDncwDc11RKW0uDRl8y+mdcZocoDEwgPcXG6K/6y3wHzPnov/zfDbAseE3lmndXthI6A46SCIEScEGc3QedaaQzRo6Ep0qQmj5VPxLA3VMKDL2epW/hwg6//XvZ3dSmqlH4T+/+DdskcjWoCX7Gm7JC5fjt5N7knlcd3zHYrtwNm/9ZqClLbieNAJwC6GlJIwQ+MwtZ43z/kMFncRXz1umVmoL++wDAx2V0kRijZgj9eKDprrBZGXYS5HWFZjn4ceA6kjuB5jh5mkd7D+A/YtQd8Wt15kxydIb1JCJBT7xAvbD6LvQvCokPpSZrfvIN5mrI/Kndn8NY9AUQmpLlr1U6UZQkDPLHmvVNpv+Dnnaf1iaePSYV2SGZD+t0/CdGhmnfJ0+EMoeUSAXieto55chzPC8C61lC67WarDfCEDycyeNTpb5ZgH7QZa+/uST6c5QAn9M+P6hCxSRP61gXSBeRgoewsatnJE5Ob93KqUbbFSC6b4vK3cWuZvJ8uBPevh8KD5FYZhPQXijUw27w7bETmcd56b9OAFWv+YdBo56c0zcWAj0DDFZT818TpBr+hU0s=
  template:
    metadata:
      name: airflow-connections
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
