---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AIRFLOW_CONN_MY_POSTGRES: AgAesB0E10MXAFf2tcQ95UNnDdLPj0s+lAgwmc+kItureeLWb3OfwJmu+W84kOhftrFkp88c7NWlbOLA4SHpiOvg+HP5w2cd2vV+bKU6EUIYfV62mcKDOLnIkx1E10R3t+rbHNdOcVqMcvTMm5R5rhRyDRXBjPE6Q7Uiji/e+/V0cXAafSLCFxQw7h/8bKWCxr9qtkklYt6a7Lk4+ywXCZvESmEsOho4CkByEH12XftqvGo1NhDvBsa5lU2DdlhJKiNI2PejFPHp+x6mtYgB9xukcs/NXu79FnHvSDAsB/t8pfFu3et78EC6Acx23I8ZIE/HscBLhh70ce9XJGxRA1Mv2Yf6BkPZ6DhIJvXJpXc9MXMgUzGbnwKG2+f+QUUJj9rB1PlG8g19Yc9hnqY5pxiMRAdXLsVB3PqYPRISTvu+fpTrftiv+OfXoxTEO+URc9EY9OkESHxLeJl3TsZYvZ0Ab7RMKs2kMKWgXJ2qYbSkIuVrGqQr6XPW0ndxtTnaUgs3eOtR8B0343aifus9Pr/BzOJvWZ4YLZl4EwqdVO6DbwqrmiAhWJ3flmLWJH+Xj+fIFD2wUuOMYJ8zr5hC408LgdFiG9M0hEHL4mIfpQ4LnWpm6ytOb4ed5h/X4EyAP9AHi2z/GFVyKBQ0LKPB7TMJ3SwN5kmepRmOJTOitZ/MmiuT1VzRd5SQ1401SgvYWEyrViGQBD205fOwWb6FUwfbGq16IS3JTOfOcq6SLH0BQn1iXqq8YOlBKUirnyX7DDiUjM3MOg==
  template:
    metadata:
      name: airflow-connections
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
