---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: oauth2-proxy
    namespace: oauth2-proxy
  values:
    config:
      clientID: traefik-dashboard
      clientSecret: traefik-dex-client-secret
      cookieSecret: fc3276bd001f7b4f31dcc9bbcbca9031
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://dex.k8s.shubhamtatvamasi.com
      redirect-url: https://traefik.k8s.shubhamtatvamasi.com/oauth2/callback
      email-domain: "*"
      upstream: static://200
      reverse-proxy: "true"
      set-xauthrequest: "true"
      pass-access-token: "true"
      skip-provider-button: "false"
      approval-prompt: "auto"
      cookie-secure: "true"
      whitelist-domain: .k8s.shubhamtatvamasi.com
      cookie-domain: .k8s.shubhamtatvamasi.com
