---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy-cookie
  namespace: oauth2-proxy
spec:
  dependsOn:
  - name: sealed-secrets
    namespace: flux-system
  force: false
  interval: 10m0s
  path: ./secrets/sealed-secrets/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
