---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: airflow-one
  namespace: airflow-one
spec:
  inputs:
    - service: "airflow-base"
      path: "./infrastructure/airflow/base"
    - service: "postgres"
      path: "./infrastructure/airflow/postgres"
      dependsOn: "airflow-base"
    - service: "airflow"
      path: "./infrastructure/airflow/airflow"
      dependsOn: "postgres"
  resourcesTemplate: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.service >>
      namespace: airflow-one
    spec:
      interval: 10m0s
      path: << inputs.path >>
      prune: true
      wait: true
      timeout: 10m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      postBuild:
        substitute:
          namespace: airflow-one
      <<- if index inputs "workers_replicas" >>
          workers_replicas: "<< index inputs "workers_replicas" >>"
      <<- end >>
      <<- if index inputs "dependsOn" >>
      dependsOn:
        - name: << index inputs "dependsOn" >>
      <<- end >>
