---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: airflow-one
  namespace: airflow-one
spec:
  inputs:
    - service: "airflow-base"
      path: "./infrastructure/airflow/base"
      dependsOn: ~
      wait: ~
      timeout: ~
      workers_replicas: ~
    - service: "postgres"
      path: "./infrastructure/airflow/postgres"
      dependsOn: "airflow-base"
      wait: "true"
      timeout: "10m"
      workers_replicas: ~
    - service: "airflow"
      path: "./infrastructure/airflow/airflow"
      dependsOn: "postgres"
      wait: ~
      timeout: ~
      workers_replicas: "1"
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: "{{ .service }}"
        namespace: airflow-one
      spec:
        interval: 10m0s
        path: "{{ .path }}"
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        postBuild:
          substitute:
            namespace: airflow-one
            workers_replicas: "{{ .workers_replicas }}"
        dependsOn:
          - name: "{{ .dependsOn }}"
        wait: "{{ .wait }}"
        timeout: "{{ .timeout }}"
