---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 10m
  chart: cloudnative-pg
  version: "0.28.3"
  sourceRef:
    name: cnpg
    kind: HelmRepository
