---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 10m
  chart: gpu-operator
  version: "v26.7.1"
  sourceRef:
    name: nvidia
    kind: HelmRepository
