---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${tls_secret_name}
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ${tls_secret_name}
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls/shubhamtatvamasi-tls
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: tls/shubhamtatvamasi-tls
        property: tls.key
    - secretKey: ca.crt
      remoteRef:
        key: tls/shubhamtatvamasi-tls
        property: ca.crt
