---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections-import-v1
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    connections.json: AgCZ0Ip/NuF2C60p5nySDTxoXG0r+XjSbzx8ubm/cvndy1L82UIXIv6kZRZUxkRqqpDYC8dC5M9XlTjdqAwOyBaDJ4FF/Sxrh0gOLC50xdn0rqIIY755uJcPhI3QUZYLUpmXsp2WiY9UIQmFN94dzOf2Htrl/yKZ0qlysSoMiiP6uPyRR/TkL9oWbV9urn3px/hEV1CCNCeQpTS0YJpcEajUHUemJqvJip1ohn+Sdbraysk1Mm2B1H0sBGgdz0yvuicaufKC5sN+pHlasAbGWzhW1fYxim9v5qigdKS1DWFtSI32C1lfGP4uajqr3wQ6jGgM7ymniWPTBxEMRLorcMW0M11eCVvxLq5ME5Ym+RSy82m8VIAb35czkSuht6X1h5y0grqJjBilRSC3CbB75tSTpK037giOVVFMi65Pe+Ejxh7jkMKHjzKbGBHk58C0k2tuECNSJ7IA1AlDdKQYo7dLFNf+sWjsQ8cT0OHVvHlj5fzUXPZZjDWFRx3azLsACiVxln547+K6lDqcDqz6Xnl7d7XoEncPcuq1d11oRKZY9islDV2RnwQitsBtj/WgWTL4zFDiEhL/IIbn0dM6bLR+MdsgrT/3Sd/BT9ahz5HC14i0HEkZ31r90JazzaHLEdy0WqTihvm4L0y8gxwK990vf1/SG4asvRuEX/fiqeLljhaF8Sil3PzylEZZwlnb2Zp1PguzbMQSEruqSYX9qEgeXsZBiNltIV+iRHBZGhyNqJL2G2Cxvvem+pm8AJKXjPdL8XjNwcyjdiNJ7fmtTpdn4STWahrNglSTpK6dkz0jzA9yq6BcWgOzuFmiCk1+VMnaR5fcdIsCllG8DPqo91T/xY8/sItH/XNGz0JPeKNWwkKgp4moWf5TqbhCvNERWLeDxw+N11O3yvKd3U6Sngqb03Z2ukJu8wD/FRhFK6TlSjmVl2362tdmGaH/6PEXmV/cm++H5UqqFQ==
  template:
    metadata:
      name: airflow-connections-import-v1
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
