---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections-import
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    connections.json: AgCjSiXKGVKepa+GG+++x2S4IYnmiMx3lBZdUCvNWMU12bMRvdxyILWpkaTtaLyRY3yGkB8y+77ECyJMollCHY+NInl0dHKuCJ3C+oET53wWJ0gVn3HJe+BBTmGJEYgi2K20P3n1dpfvTjbsUNztTyCZm7i5Diua7vJ2pn2trq7t48OGRx2jrPgC4mOOW8DBE/5Yyr4eWWqTaMsnVLIL7ew9U0/0TXescWTrA0G5tZ4w6zKaCBQGbu5pbIi7xPNXwyyHFmrKgAFpeXiARddt5e+KmMU8QOz4sN4MVFdiHY+BgA8ybgud/HBiSHSM/3RySK/ZqIrp/dj340iVop3sS/A78ZreuCjexmWdfmoHFy/YH3QsFuAvTmGitSiolOmxM8Yk9x01K4dDO6Stq4FxG4Ex0ogfygmr6S6gZIfbupgeDnCY9V8+r9HqvTzxanZ5qms0H/AHVhTS9g0MAEMN4eXJRfTiYba4+c8I70K72W26LgVxcA2f265Jd5R6zSgibxdenS7nQNUe8/9RqE/u6REpQD5aXK+vBcZOEpWEhn2RkTF+lyQlcfJ2cBsTJd1A3i9JfPOsTfAPD5jUC9Vdk7U7v7l5gXTq0XWdl/4DRf2I0N6j6yPQkgmvAI4K5xZSGeAqWXLqeKl+4fPT+o5iATsC4KZKHT2fuSRToJC+Yx/W1ezbWKm/lpgNEYCFrfODmVLv3cyWjVoTxRSARlBbXmy1GZB6UFpVW4y+iBsj+9IyuYFERgD9am9ewlQZHz2uJ9HzpwssuqLP1zQYTwY/BcIUDUOUI88uDM1auPWvQO/pCK/+RtW8wY43LgtFFM9pVlz1+SucpKPirKNjBJh7LiJn0so37rTKSnwEEpq6EGQZ/wLL3Q4UEmu7moNXgVS5yI0BiuGx0J+JX/OT+0qUqmYl6FSWhQDoAjvn4GV+WOePxPU8vo+kYR/nnfRN5y1KgKVa7P2dL5sece3BwT9JmjBt0EUudqKl194N41c+/xW5ytSSwLuls57VY0zq0uAzpdscFvbwF0Xl4JrjacBC7+zKMNg=
  template:
    metadata:
      name: airflow-connections-import
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
