---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: rustfs
    namespace: rustfs
  values:
    mode:
      standalone:
        enabled: true
      distributed:
        enabled: false
    secret:
      existingSecret: rustfs-credentials
    storageclass:
      name: ceph-filesystem
      dataStorageSize: 10Gi
      logStorageSize: 1Gi
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: "rustfs.${domain}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        enabled: true
        existingSecret:
          enabled: true
          name: rustfs-tls
