---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rustfs-credentials-sealedsecret.yaml
- helmrepository.yaml
- helmchart.yaml
- helmrelease.yaml
- rustfs-tls.yaml
