---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rustfs-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAnHYx6mZDV/3s974PbZEnNPFuHjR46QIX6ZiQLB1TCdNs3oJPPLKB/PUZxnxqAazs/WOUQUbfm1zD/USTUrN++yfQ4YzQ45GTcUgLFKgbhr8ZUeizVm+N75OQBYE4oDgRNwfj2yqackAmOPExq3xQhdW+WKzbsXT7GCygsWNaOpbrx79uoWFjOgnXjUN4n8YwVqZ3tBr/Fu/uljogjmw+Ggw1SwkHKjF3XK82BoTCDEzfeaF9klSI/m5Srb5ruFZlk9JbFm1X7agZcBHdrW8Zina1ADkFbmDyUdnMk/GnbPFc7otIVZ3ipcxIiKlhU6cLuQ7Y7dAcFluDXIl+yVlp9jtSfLoP+NY+pskezqTq8A2v2cU6RoJvWqfC5vBJf0MrwnvNPUQn2hQujB/6iQfStasELOqsb9rabIyvOW0Sp0uL8QblZyDeY5BklTDlAoMQ1AIHD5hZgnB1sRUuFWw/w6C7zmA5DHqbrhoGoVairYKPZSS9kb2MJzzgw5ui6c2lcR+QaULW2a1fBNfUwB8Z4ObOxDewvbTqHIYyovgHIDec452DjlwVVQ8ple44FqYCoZYE7t9nOEWEOb2ZYfTX7sjEsepouopXPWRXRDB02Fz0BUgJ2eVHe7xAmWpOCHr0sgZr/2pAo1Z26fXjJXfBhxFzt9PLSZotppndWDamXyFbfctgZfjJltCROQ2YJ3/pMhbCbQ/ov1sqLVQew8gpcx5ojJA==
    RUSTFS_SECRET_KEY: AgApdCXJtvu7O0peKi6fKuN3SVeIjMdWqRO1Uzt/ufb0owiX+dJLGg+i659IyXJ83hOTNsEL6hdjLLirn0u5bv6aJKGp5sf/rwB6L+9c7UzMbztYUHgd7y//AI51VpEi1FqbP2g7Lp/f2iyygP2ilzxrKD+FEHx+5HBrkM70///cfGaXntX2WarCGWjT03hU2UscshMzk0Zi3ybVCnSbfizhxT6zlQrTnya461r4K6AXnJKvreplbSGHPVvo4gt5Nl87sAfmcPkQctXt0qrLdHkCwKhLD3tGLYCcFl9PqlqCGl5T5ZpOnvs1g8IlBpc9vstt2OeG3f1pLcPp/tnSMTgvIhVvO812OmJ7zXexOSx5q8f3h3ZEVGi7XByhmfurWnoJri2xFo+Cozbvz9mdxHxr5G13OXE4sVp/5Vc+PzsTXls8cDGrKqpyrQOT4HYxxSMFmINUpb0JFwL4+euP7HgyIniMTseCZdPt2/0Vql4r5Ks/EkEpa1mvMtuC74UogekpOWy3ulaO6oiag1yr1+1HtolABo0KnrBKhpbpaSULhjTvWtQOnpv/jN/oC5TNTEMgodGpOr6sMeUuEPutJe45mrafdUeFQiy4e+m/0bdGvAyVTaUPHAMoh34CCr2c5XsSJ2+i7bHVL0SgM5kbidfeXjLkTqVl1M8Sr3pF2OtHfG/sPzTAsK0EEFcvAHHeaVwqdaXJSg0H052QNualCW/6jNHc+Ef90j01rLMUEClbjqcD4uIuQVNb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rustfs-credentials
    type: Opaque
