---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rustfs-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCCpM/x1Mn79Vfi538MP06ilrt5Gb5pek99773qQYOQL+Es8d2/HQhDgt1YbmyGwfaeJCYEuuUMpXsHLGhYqd/PHcj6uIEyBi7XJLKLeVaAQqITw+z7hQl1HfHYKFLeGpKhTKBkEGRO/BEBvM6JgG0VyArf4QQZoiloR4F8iULoLQ2K/H4y7WGNIyRa+/OAhWSYHi0ICGXFHbK7S5Zh4y7gThGM3BqADg28mqZKtevYOXtJXUM9tYN8aVDq2jOHoxHV35iytlVcuAc7paYkpch/N2E4iLktx7N5URC5HhWo1gYwUgoRJX3XiEEj8O1wn6BH1IYKx41sKHhEOcmLklBmBgZIIP3MjAptZdDeAjSkQyJjc3OVs7krOilKuM02iyVosKFkypeHeMKZJiCCpA3p9F81Zcic4DqIMys9Lq847RMBTCUdbimvaq8kJukTgTdmS3qAbJY0n+iadicEXtiAuLW0WALOOqQQX9zZFUn6FmZ3SoyquZ3hcYNoPg2YYb3rEKG/LyoaTUHsV2gyVOymXfVQNlsAqY6OPkWyLl5l0f5v4oEWP2iUc7DM1W568Q/rS1dN6GJocDnc0F2BO8Mn9meSAJGBXpBPCITpbUSCF8YYGZfDv8FtknakAVffvZ/YZwkv4qVEEAKycb0CqevssSDNbh/59XrMVZcjwS39zXxZURsqivx/1xnbFz9DDHZ0sXxjuwVHkyho4QpWguRrt4LP1w==
    RUSTFS_SECRET_KEY: AgCBr3cieOufBARG9OqYlNyn5JjeEumAPoeS7fPHpuilsvnU+AuXMp53AKzPpVD7FT9sdj0DcbsONES5eLznLmDysULyA+Q6X+65yBCPDkzUWKui5VIXW+5u885IBfVqQFv1ZaBXwBPrqxhmg/UNhADquv8ibnY0W36IhXMg22TyX2vBmg4qPWeGM/kMmB59umOlla1zxrvR2G7RIaYskZOWT7Qv6EWJBvwP+Lbhv0h5cNEyGBh74O72WnBhUGyrG4oS6/iOXc1CFEODWtB2Z1+y6xtldoplq67/SvviuiXDWJ228AVdkkq+xa9FASm2iQ7UNdVwNpye5HvX8IdWjZoQCCy0Vg98LaVLSaspflb4PlIj5qXAgJWJwHROuAuiE6WkqybzLtY52lkUreHfxOyvskbPPvRBRHJlizPufIcb/0Gd9HBzH2Fk8CqXtWpco0SqUKAJNhpLfEKa9mRLO7Id+lsNsRXNjAZXOd3olcSpsGQGLAcL53noVKHm7sb32SoEGihmY/OE9nyvExyObSi0O29lTyyCUk6QK4nkMV7LF12DrBjeYpLOO770bLDhCaYwLueLZD59rlz4rqJ9ei2njpsFKuWuCwO7O59Y7D7aH5pE4mL81M1ksd9nzM9br0+YVWnD0emTfJnrGAEHarL1u4i5jHKijohLw4OA7r0qcG1HfdyVcFERXcC1dO+fKMZfq3Wx1KOg3b/YgVM7OVTrFTfqZ3FAHvWmjQ1loCU/6GRLCNxiThqp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rustfs-credentials
    type: Opaque
