---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rustfs-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCSq3f7e3y4CN2YPA9F8OwKR4lJPLHZz9MbrusXtvvfyqgi3ZwIcVKA8PcpWhT4LzO1FPjyKmVRqZL/GYu3Vi8CWJUNaKzKB1CPSYM3lHXVYFSuxfWfP7Z7piJDWv0wqeGyJPoDAuAnxjG7AgAHkkzw+3nMkF2hFEQrywoJaFKYCulexUBJjgqnURTeqW0E6aqGwpWyR1CSx+r3Gzxme5rAAiiCRGNvveCA+sTLaIeabGGzBnvej2wnU38AU0YsfwmwOwIwCi35xjYMB9rGA/YX47n6i+0RkYtWd9R7ZgNXIYR+14oCEPgSpUcc0hUyKy8Thw3xOQ7Oj+sBBlh0PtbTbT+zxo4mOLQ+bCkzzbn/PMdsFSSJdgNmhZnEjbmwRK1qg0/YvMkL8N8b+7wIetkRQU0IVmeTwrv5fl9USSiDXAr2ILYearmJlhlw5mMowOwVKhJH1me/JhGuidOMezhoMnWj/UrwdlkcFMN58C7TjNeuaIbDYN3JeoZ6ZDQBKVY7+QLqJHHu18x90eFIvyyx5uqmX9IF+z79g/KoCMsYmH7+I9cxPdHgX81rXvwOASYtMU+n1PPPMPfut/pARpB2zMMJQWjusQo8j7pacjZ35VreYu8mTuNSuz+hFL1MosnajVRL+Ny79yIC8j7MiqyhDGyfUKV/Ae8ZM4lbt4fxDw6YQuHur3BVSkeNwuhakMNTNt0PwPU0jxPEZKoQh1982K5wIw==
    RUSTFS_SECRET_KEY: AgChKlYOy+Z/+ApbBZXUFTWnII9ReaFlwLveeDbsNY9hyFG+k1Xg7bhM3FmTHn0FSi6kSsXyjcGaYFacuNCXhCCpuHYPKXZg+rotdfkcg6UenkfUnRdGbXj8buMMH1KlfCSZjeEDFbqCwEJwMc01iijISGeGk2P+cx9mLfShK2ArqXW0XIgXxnmi9T1NXd/FO9aowGXdIi+Y8oJbz0H/FWz7WKoUqUVMyE8uf/2w/chmYISWzmKIQmMrx7LfK3LaHs8AsfpR8CkGR5StT0BKs1szbz/8Jtv2mL0CQVqeNfL+F9Btv7O1efoOGnaSL8J+Tpa6iOz6aJYMnBkGZoYEq2cEP1WfjWNYuSWlaBut4Hc/q5ZzB8yApI2c7Qx+ee8YD4ytX5Ey5VySeDqR7nMzJuv7YlxMpoi/3ewXyH8OGWIiMdiRDaeE79kIh7DLSSyA4kd0G66IHrT1TagUa5krapOXInPM7DQ/D30vleNt5LJAV91o/jkes2foqMV1QigtfFCYgR+BHVyW2L6JHG3x2xN+XrWjqPeJ276ae11huxTR3UQICDZQ73l2b+uJYTEPXGLy4crMj3VX3GyZqFQcUFf+lGO+30+PCrZoyrOUcL25W1jen5VhwaaI/kGUmNcuWvQFicTpM5EwMXMN12WtoY92TxF3vZ7AfHDwuTCsQWo8oe7z3xcpQcnPHKTKBreadsi4zyXonlkt3G/Q0h8sTAXzcRJGUGCQYsAI/Vo1gXNqYheW7PArgt31
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rustfs-credentials
