---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 10m
  chart: portainer
  version: "239.3.1"
  sourceRef:
    name: portainer
    kind: HelmRepository
