---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-ce
  namespace: portainer
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: portainer
    namespace: portainer
  values:
    image:
      tag: 2.43.0
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: portainer-ce.${domain}
          paths:
            - path: /
      tls:
        - secretName: portainer-tls
          hosts:
            - portainer-ce.${domain}
    tls:
      existingSecret: portainer-tls
    persistence:
      annotations:
        helm.sh/resource-policy: keep
