---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-connections-import
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-connections-import
  data:
    - secretKey: connections.yaml
      remoteRef:
        key: airflow/connections-import
        property: connections.yaml
