---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/nvidia-droplet/resourceset
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      domain: nvidia-droplet.shubhamtatvamasi.com
      # droplet public IP (eth0), handed to traefik via cilium LB-IPAM
      traefik_lb_ip: 147.182.157.234
