---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-ai-gateway-crds
  namespace: envoy-ai-gateway-system
spec:
  interval: 10m
  url: oci://docker.io/envoyproxy/ai-gateway-crds-helm
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "v1.1.0"
