---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  dependsOn:
  - name: sealed-secrets
    namespace: flux-system
  force: false
  interval: 10m0s
  path: ./secrets/tls/shubhamtatvamasi-tls
  postBuild:
    substitute:
      tls_secret_name: harbor-tls
      namespace: harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
