---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart: nextcloud
  version: "9.2.6"
  sourceRef:
    name: nextcloud
    kind: HelmRepository
