---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-fernet-key
  namespace: airflow
spec:
  encryptedData:
    fernet-key: AgCQoOUaI3Nik/hS9vBaQUV/jfPlktIYwtZX7bwaoPgtgK6D1eHYZAW96EHpBmSm1iCEQU4pb1cUefQzqf1XXQALSMPpsjqCuynX07J7AkiReXPLA5rDT5B1CapcUPFHOK83ZOKzjOiYLk7SSd6UvdqfarGEuX5jDD7N5bvu88ePcueYFF8G7DqVDRaGdSlq27Y/hZFnkffml63/GwHVfUNg+cKWE1AeOBymJOwLeYEr6anqySNSXHTgtjhPoRXaPXrGKRIwExnAbjsiK4qhDdSxJYMy8xK0OUOKelH3xBLuz4028LaCKTcDj1B8I7UqPZ7xxd5tOHGopEx+SLeLkTdtNavCIMTkqWkYZnn3U9ZUCaa8t7Bbw5XCn84Q96rWNKNijqvMudQna2sinwLESwAocg68M6YIFfyQ8fvXhppSCju+GgYQreeS1riWLxNWdqitJND3UKwDypkdyblsf2mU8qA7/3aVSCPzfBpvqYcJna3qLVwd8nsSD/5LCu2Okn7WgAMGs3fz9I7WuOXXRL6QYw93SZPac/IntCnEUNK8apPfVVFJXRQ3Lp9XMMzKdgh1m3n/dkn0HfR6gYojcvBHrCFWnIk2VNXA7qLKLW6Z4s4fIfpgKBHkyUBm/e3GmXgFrbkf0hjprhqQO4oEwqhot++IyUZgcGwqNECrA5Rtc8hrdRLQ/Z+3dXqyfhYZnGH6VBF+oHQ5fTNJehFU48/UgxPUJYxjCU6hYQLYyk0P2vXuWkl+OgGRNQTW4Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-fernet-key
      namespace: airflow
