---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-postgresql-auth
  namespace: infisical
spec:
  encryptedData:
    password: AgCL9S9Bq6ueg+iZ3qzJHjTHwdXdan7pKxmxlZ+fJeD7V0nv+sXRZmwwkZtU8/mdZL6h/rTuUVxWNIV0piY3x3DM7XJB9c7mqUg9fHdMYFDvGaqaxD/CiSrvhim3KZcTbIxmwp02EhdcHNup3SA93taatVrY6uryWV3pRQfflwpRknsFbBDyEecfQDeQCL+1cCrH9+J3L+fH4qchQWud+SD/ozSnL1jBSbXAetQSWYD1UtXtA5uyDv99p1cR9yoikudbm6QTA7utLjuYZqDk3Tex939EAekt+Gvce8ZwsMwvpHNqqzC1LY+qUKPZI8KfBpANxqIN0CPY3V/u7g42TG8Fg3h+zQXS8JLQ6a094bdc+qPzJf73dLCtAZ8iPw/559gzYbb/fLkuZUYmD2PCOtYAjkhZVDcD+QRNdKdQyDS6UFs8drjuf2L592kEEqB/7xHFJDtN00lvhsnyPoGlcMY472LYtaadIxAzX3usRoDyaK33hYaraN+fILchn8au0GxoP2R9NmeKN9hGX+dz92a6p7O4hcRO+uCWGYcvFwS+2MVU2HCtWSZKcayBfVABtVOjZ2kaYjfGv0gMIVR6sqz3fJiuCrUhvQS5euc6oVV0UJWI7K998SkFtXuaNlIgjgbgEQD2a8PzoJxxNFkBRityS01QTcrYJcKlW7Mtv2WCvTb1TaGPdS32x4v8Yr8vzsnR5WITCV1cyGBcPQ5CtZLbyN/hfGWpiHYhPUPt4MfQ
    postgres-password: AgBl9Riud0wuVQC5TEu5cMG6GfNBds4+RBx6MPbTkrRQnPf40ZWRJcI474dg7Z7JZ5os43NFiLGz+DfYvdcpwMRB7PtU0dJml7kPQ5N/Zp1h03ILl7ShvgrZiQ4Hy275G4PHRQoMPL5kO9gMLETNupaWp1XpKiBeJtpeU7UJPTfuahRdb5i5ZxztwL9IgZC/lidHcPF0ndyEc6zJPPGNq3SKspQKRNC1KFNshdwSOC40BMu01mRsy8oorfz2FmSgtsFZtymEKMeHs73yZ+4Hw1T0ALe6XE/dZOpYL+Q+JR9uVm6WuSeQIt5YWTW2r2I+Nht2rF/ia7P8u8A3d/nFWD2e+Vr+u8FNWIuvCTYkkqhzVtMj3zyjILnJ6QPC2KPL7GlcT6E6+cMgp3W7vULNPXYX1+PO8lFEYFDosii+N7v73m5PqH2Luv1XUuO0m77+X1NF2XyRAPxrBZvyxW1vR2VmdsEELzi7qghbpQhNV9p30tLUaSwRWpcyAyFM5C4G2maaGy8xq/vX/aoH5R0jDjboGSC5l17zcOTV3ZIeXZHmTteErJrqPD1cbuvx0S0hc8Nnz/63n/GEbSccJZckqjGG0j/4Kdi2sf8p9EUaGu80I9kb9J9UbAQpYdSua7usfdvtbyGUn90dtGJ9BAwYiupthmTvC5z6eZjUVu3aRfnOigLYts99+EDMdNjbhGswRKkeraMZoVluEK5mKt7w/VwGELMNQctWeqHy02SHTYMa
  template:
    metadata:
      name: infisical-postgresql-auth
      namespace: infisical
