---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-redis-auth
  namespace: infisical
spec:
  encryptedData:
    redis-password: AgB0y9L2vTub9gt6340qotfJ2bZRf6i0LQn+uBNoJx4vL5sWggwt/0tsSS7Uxo2oZXpskvtOowuO6VJ85jjt6/1KIZcfsYhoQW4jVnnmXNoZqyyZmzeyKrMT0dqZViodhO5adxPIFPAU6tS3DLHf9nROqlI4xS6wuwsygl0bqwwNbzT8SbtzwojCeVdkI2fRiqv7c/xNFB3I4QWpHhCQWWW+sXkhLrjbq8QklCcbMX+vIvFpzmWlgvuZSNY1M+Z2EvFASCJvaOm8I//wkMVe3/Mq7NGQWUMEQ5wrj/5f/wCvqRsJXXnuVyqP3f1B/vsFsP/6Ij6QrOnZ6hrOpRBwIXRNCx1lm/jYttnKUBRvUnfZP3XxC9h7tY0azF/DLeYh5uBwKKo45fmusNIuiKzABdAKX88j29/a4yWc6Q06AYfEiGgwBbIYAlY23aGH9bhd7rwQBnmXUJI6E7omUpKsqImMUWVpQDU2beZVFkVAspGy1w48SVElcn62QejBttsLGHXGbqkUx5kOUH4XxS0WX1eHzDYyXJ4x719ViWLYOO61EAf7SwvlxqEaLUuujIVtUC2nDdQyYgeupUdue9h3EC9z+HkLLxztXRvF58EKCXnq9Da5WzCVH/qfrGpzX112VXYpkF9r/b1Nonf2HxsrFL6QmDMtjhVb0ugk7LTidbqM0jy7vQl5BDAi2os24De4xcGv3hZxWkoVO2FUzynUygwCejQhBeNBPe4NZtuG5u0=
  template:
    metadata:
      name: infisical-redis-auth
      namespace: infisical
