---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-basic-auth
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgAWg5VaEcr4XYHYHchbrmVbZdP0XoGB3Cl0ZrTjjG2yo0tiIXGfRQYNOdgaP/qRNOeU21IkgdtsHQrY+u83Uv9X6CHskeWOHL9s1QlcNBLRbmEHyP0kVzKKopXr7S7J0079rUVnMZOSHYCkNeEGwdFH/fgho/LflxL/okrwWlBuHS0dVvfoPyVjCvnwXdtgbvcj8LZhW/biAt9uIVhEnekZ9hvQWgbgT3kEsj7RG6NyP10GD6eiHeCf5WXnU5JVeAirgIHPd0sCwuUdxaWEyl/9fg5wz2+06bw7oxhrH/6r8YxY/hhdhd6D1C5tmAB9kE/ovula6CGqXLLe6QovqrLrbztNCVJv3DQ/Kr/3xaA9O62aLNtW0TGKqBFLeryrNJ1AWN/jPxT9WFs37f1C+j4Yybsu3eDiMgGiXLGxRTK6/XLT3HfNVjj668nPZVk+51X5HXn0OIS1bokgBUxUayu/g7laye8opMrjVcF60hIVRIWE3KcfAFU7lNyWyHDdX44Mh5azjQan8S/0tVjia+qZemKy7fHGDSZn2dQmlZXOj83+HP86dkAha56JNMbYkOMPFwzRsiAsiwrSBusqTNQSLPuAgu/CfFEbkxR65cpEv9Hk50Up4HwBoQJ0DOJGEiDpMbIHMx14BcH0X5MoBq3wtEisKN6LlocDxnMGbZ1hYkz/lRpFFURH/ANEfQeuRfCw+yvYeIBw
    username: AgAmnDVQI+DE0OvWtANqu3ViHHZKHRN7jXzqgzQfSZC+rLPMYJxQmb5gCklGDvK5qAEcL4VOPDIYRgdYQaT53DTA/ocoUko6AArzxTJbc2gLnLvhLv883vibQr+VrikeaBuD6eYC7UL6vr9CBhZ6iVW9Q5PBzysO3irt1g7jm49P/gxlzEi9x/7SyevPJNCe2Dw+T8xg0W2rmY403z9iBktKOOdZ2+eONGaPXnOdpHb8zGyh7pcj72UIb3Vi9G6tWMLVpOVAL13B281CGPzjOg/zZw/y6Cqygm4ORfOLvjkMUQzgZogPCSxY0UTCPjYkTBnk3l+3nbelJEEHHnAIZGWlnxiaHisc0yc0Tkrsp8ItQS2e5SzXs2YmwbV+8tfaxDNe1/Wx90Ego+kk+eqQisnmGLRbvyoFqm91AHltUTwlI3mjaoVWvPKVVTqhrPLEM/nS9/FyvmEuOnyZ0Cm98TFLg2wlNXnVRiYcCJB9Nqszt4XzqJo3rjwi9NFn1+/Ou9sP03JYwNvo/voz1w2H3yvR0SwkeRVIMJMJ5Ew80BTocK5XL6/ApFNEPuB5uWXuqk0TZ1tP0paV050XoUrpCclqL9KaRKduV+FEj12DMgWAViO9NJF3UX1sRTSqXrXYCXhI1bKIxaQ7R7hXun1LOz+QUaR+Thhj97gFTNkuJXdt6LEcdFBCr9lwrqAU2b0SzOmDAHOYdrb9
  template:
    metadata:
      name: airflow-basic-auth
      namespace: cnpg-system
    type: kubernetes.io/basic-auth
