---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata-connection
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-metadata-connection
  data:
    - secretKey: connection
      remoteRef:
        key: airflow/metadata-connection
        property: connection
    - secretKey: kedaConnection
      remoteRef:
        key: airflow/metadata-connection
        property: kedaConnection
