---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: teleport
    namespace: teleport
  values:
    clusterName: teleport.k9s.shubhamtatvamasi.com
    operator:
      enabled: true
    acme: false
    highAvailability:
      certManager:
        enabled: false
    tls:
      existingSecretName: teleport-tls
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 10.10.10.17
    proxy:
      highAvailability:
        replicaCount: 1
    auth:
      teleportConfig:
        auth_service:
          session_recording: proxy
