---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgres
  namespace: airflow
spec:
  interval: 10m
  url: oci://registry-1.docker.io/cloudpirates/postgres
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "^0.18.3"
