---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-credentials
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    GITSYNC_PASSWORD: AgATdkU1A7fBlrN8OUOWp2CJHWOYtFC6XhkFR5XY4NxtCUWvEes/AkdZ0Rgzu8TePYrYF9hushGxpxwEb63QvOG8ziuxRzJEgtTsXyoeDaaWE4w2nV6qfQYVzQ9ljRIE/QtAY728LbWp8YOVXPMWWYeeU1SwDbXtyms5m8y/ta+zhckEjX8/r/pNmQSKOW7AHvtBqQhcjSLhZvHwuOaLVH38irV9WVB/Uf6ubb3yhUloeM4Vjyo2d3F+zrwMtNIexsQrpQKUiMluOk/+LHq9QR2OUNzmFqcH6tMplfWG5ydrDEsTjSyOA4feBibr9ykmFr1hSxhMWVCCRqzWWhTbLF7cQFqaVC2IE9wy2TXHRczLt+yyjRlRjh3D7ojfeQxyPNK6TYhq4pyWaZXjAMLyrMcBn/0O91k/BfYx5dQd4tS2GO5ec74ND5VebtC0WGBvS5zdbF+TjDNFWEFJrO3JXC3Xm97IchHZ5KJcOKKRlEtJ/mNAmHCU1Dulf0OFgXEHWasFhGiPn4/xdZpjIWWFFPWSUTFWfSIup7b8OaWkL2XjwFT0PFLBL2mV5z98kHyMz+rOBv2DdiKoOxxEO5k1rhkcXe46EDQ1EImuC9K49feMKATpPnPcJv4CziukdemV4KDwglPdfa59E15kduWwOE5dqIoOr0Kr3trlbVwE77aaSSmzdKXAQTLmWQ4P8KZjsrQksR8Sjswg3po7J0ePuSGpaW7KnSjmosC1AEE6YX1yv7qedw2cSpLiF/u2tjGrPMfBPAypfuKKTD1bCjrq1dgdObxx3q09cfuzii41AzzlzrO7tHledGLpZtLCRDA=
    GITSYNC_USERNAME: AgB15+ONpclrz+TbdSQNNj17S7ReCKyxaNEq/6IX4GhHS8rA/WhjcBEbcrou3rz+5nClo/rQmcuD+qFy9kT0GK5LyC0/KABNUdw2GuJ7y8XnH9gg1KmcOQn4gOeaO2UU0BgkUke2tAivHNfrHDdjwSLxFanU5UyUG6ca6+wTvfqsy2KsJuWEo4IszWJcaatJcKMfxgoLzBCO63K7DXz6jjEcG2xu05apDC9uiBfwR/371n+HVsNe4KNqWtf0FPPtfa2X7QC2AkNMFY6qaZlybvq2le7UMHN/RFb9bk2Nf6Y9kxoELeGt2fISwdbf0wy4fRISuwGFzK5doT4T1MJX4YbSH43y2wW1nr8wEuXEJwiwuNGxABTjhnaGJA32uaEoIiSKJycLZM49FeOluOv668P4f9Fp2mMuD632hrHw2uAglCztTmRK9Am5kpOKXlUc0Box0G4JZfLiYJwlO0ncLRBcdDoBEuvLLYopy5I6gAzXJFOgCrxWJAYxWxdvK5aIfVzanhzYszzWgyILn47H+PQQg6zy7HglUR0dxycOOy09eZsmekcqNcazKN53dbwe9REXRH9yUTaOF+3kVAbEDOMJZ9oHLfDfNBYkAsPtdalFCgmGcHm5QGpAABX0QmQDTKBgG/qbf/dcGc/RRLXWI+Ac3VM+H7kcRnnd0F6PSQJuN4kHbqArk10CCw7nVL9jxV2mG58=
  template:
    metadata:
      name: git-credentials
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
