---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-opensearch-connection
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-opensearch-connection
  data:
    - secretKey: connection
      remoteRef:
        key: airflow/opensearch-connection
        property: connection
    - secretKey: password
      remoteRef:
        key: airflow/opensearch-connection
        property: password
    - secretKey: username
      remoteRef:
        key: airflow/opensearch-connection
        property: username
