---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ceph-health-fsid-alias
  namespace: rook-ceph
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: ceph-health-fsid-alias
      rules:
        - record: ceph_health_status
          expr: label_replace(ceph_health_status, "cluster", "d582a71e-b08c-472e-a697-6fb744eee41a", "cluster", "rook-ceph")
          labels:
            fsid_alias: "true"
