---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata-connection
  namespace: airflow
spec:
  encryptedData:
    connection: AgCiUsX93PqkBhEs4JcQ8HlQGAUmKiusia3Eq9XHt67R2wcBSlBC85SAMk1uhHgfFccRA/NS3JeMMyH9FyMJM/tdHFEAkDIw1w+1v/umZg1fuAiMWdney/XqmGVaP/ZmPj0zceAOh0tR/CzgYpa5et/OQr/n2Erm0n07mCouiVOllxcokSJAc8TnkitZLh8pN6XAjzASdtGFVEwxhWuMj8N4YW7pCVeKQZ2x4PPXE27TSkU0cB/BuU5z1BbauW8u8iaR0r8fjeFpffCoG+9zijjqPbtzdjd5ZnVDHHLvEdzTe9eMMmZLbuI2dK5Ixce7T4A1iO3dXrAKa988XRuHoBnSCBdmQLNTLJbrZffPlV41OzJp8Ny8mmEbOqe5b8dvLB2Zigua7m4mQJnoJNbCzwVSgffVvXknlNFlk8nkbvCcOTNPeGfi5MIF0i3E31fdyxMBgkTyswd19lFGbyhvO3ueGOpo9RRkduyDIjgDph/zSc+MY5Vjv6X7vxYicc7uU9J6ULeI05JeQPSm+CbmqnfhhCHHRUmTmpc9zl5fiml/bYdyNEkSrypi+UBYc20y6+uJuTabr2Kj7jyHiGmUOpCv7zyZv3hDL+wNcqTi3jUXPYzT05oKZXbZmNQjdIxrNEBlwq+GC2bQJk4NWPPx3Cf4Cj6S3iCJ8Xi97jbkIXepNDShTEfS1n45inzmWW/Q1J1e3HT2UI9liYbxMWmYxeAMQDYh2PxMvsYhsyUiESL9hwWsvV/T5GgsIGCaK7uLjRecLbVsqP+zjlIbl1aTptztYJOwEwaXRvWTovdI2uMaxt8=
  template:
    metadata:
      name: airflow-metadata-connection
      namespace: airflow
