---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: seaweedfs
    namespace: seaweedfs
  values:
    master:
      enabled: false
    volume:
      enabled: false
    filer:
      enabled: false
    s3:
      enabled: false
    allInOne:
      enabled: true
      replicas: 1
      s3:
        enabled: true
      data:
        type: persistentVolumeClaim
        size: 10Gi
