---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AIRFLOW_CONN_MY_POSTGRES: AgBdUKdHKsu/zZAC+R1wEFXWRRt6xAbCmN/yQpnCwddUSZo5ZbBcGJ9lSOWw0cgKNVgh+aUFpz0t37Je2KH4/FGjorkxxmdfTkr8XsXG2zs0MV856VugMpbobZ19PG3+qohBafuJwa7s11hw7ls6/laYKASewO/xsAgBYVgWNKaLdWOmiroE0OYkPQSLKq54LU+frx5du7W1HR4Y6ySCJXEKlD4wapHJv2ZY0rXvTLwEAPAndIfjoa7PoyToVblkmmmb600/ulsFtH29By+n6F49HsXJ0yRHIBr50cS4qCokP46uo0SSVywnyyPcM5C4zH2eS6DV0GpPQRSL1O7NL2H8IBMDE44A7uHHnYSnMA5hHxHqN8tzJyokaBc2d/agU68Mowg7RfgBTerBT+0UUtM92VkY297v4wj4yxouiGQUNm0xZldsvJbOcjtxzKlxrpmOXagg9dEhdxw+MXkbGoOsiT0lWcq1btA9fMffKMwMq3//aaG/fTrBayzg2z1Hoczb5gY6jhp5RfOEz82OTmOMedk35E488aP5C255HuzTS1VKNtgkHCfXpkXzdGXiqhoGW2RmKnZ7FFvr/ILJ8JFzQQY1u8i0CJzVIfwsQqxC6sBMIC/jSqfNU90CjM3kViTxmAsvT40wsutBLUAMULFa5dlm6iVtZyDcJ/uleioZHycpxmXcny2P7t8cC9K5RudalHiEjlYbfQJf8Kos2hOCvs5xkcucBBd5vSjSG8XJLztXsR37atJQrJL+CpHjqKrCjzY=
  template:
    metadata:
      name: airflow-connections
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
