---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AIRFLOW_CONN_MY_POSTGRES: AgCfulbhKY+Brf/Io7Ls9uFq14Oepy+mFY16nMy93G2ciQOhpWUjOXsVi1zy+dBteoxnP+f5tl7eUcWVTjDxhQarKFN4NlJvR0pn3rH/lAsRzSM/5QlWnVtn+Mb/T5F/XsrjX2Me/PIcC7MKw4vsFjFAMDSpdC8hoqmRB9dcRB47MgON2mgzpRE/RI6KpHWOMtYbraENvs8rZEYj2EjOE+SNbKZbE1FH/fTQICQl0ADVDx50CObEabzoA1iqPIfsWd38ENdG9HaUw7St5M2JYGBnBxLd/9E0xaloQTgLo5UX1zAGS7DXsl7pyfO7SF1ZkDui+By/V1ceKU1lNgGFNZJeng0jW9kP7U+cAXzcKvMh0dfB3rgt6iFFaEEZdUVo86DxI2Mlh/eYPFMMGBrbioHjC3hjNVlEhEodY6BqZvmJQVV25trDQCvAVqFVAW52PUm2LHZHsdGlTIuE2zGzvqffWWeX/jGnwTEnwbAlvzvEeZMvSUw6BRoCKk5+QZKymA4fjWQqeLEUOVuXZRe0CawiS7r71eQyNZ7cYq5rXX3vJnJ+61PJ1Og1PoBnrhdbI18oVgFgJImlNvam5ko1NSmVP2KKop5MATUW1+d3M8Omu/AdpRNDSvyAfINLwPPl5vwHUOlTv55f0I/hyCQ0gU92w2iTUna3owvSRxh1azT27gOiiYOS4d65hc603cNsI39vEvGmg1k5W7CvoAKMhjMwes7pbtqN6rxawxNx1oHfq0gVpkWVY4LzbFgGR0Q5S3xXnxumNA==
  template:
    metadata:
      name: airflow-connections
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
