---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: traefik
  values:
    logs:
      access:
        enabled: true
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          namespace: traefik
          labels:
            release: kube-prometheus-stack
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 8443
          protocol: HTTPS
          namespacePolicy:
            from: All
          certificateRefs:
            - name: traefik-tls
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.k8s.shubhamtatvamasi.com`)
        entryPoints:
          - websecure
        middlewares:
          - name: oauth2-proxy-errors
            namespace: traefik
          - name: oauth2-proxy-auth
            namespace: traefik
        tls:
          secretName: traefik-tls
