---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: traefik
  values:
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.k8s.shubhamtatvamasi.com`)
        entryPoints:
          - websecure
        tls:
          secretName: traefik-tls
