---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart: metallb
  version: "0.16.1"
  sourceRef:
    name: metallb
    kind: HelmRepository
