---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-admin-credentials
  namespace: ${namespace}
spec:
  encryptedData:
    password: AgB5h3y55qNFeSCrVuHE0FW/Xeo4l1sqXjZQlz/ZLKlhbLo0adNDQ8vzXOKEhJQDgYvBru05wbwf6j9+yKoiF9gGmChhPo57evPHpyUin7pmGZ+Je2fDQX5CSQwgot2/2IrURrfOe17lwF/Bp8Vz4eB0bJ07EQSbCjedDy9hYuOjiNMSMx/6nPjLjiEMJqRnJgQysw3nRN92/4cqCHQxRkYbIldez8iYCwPBACkdbPTC8Rug5V2VGi18NpfZob1ff9zm4VW8XLwUQCUUni9b3FbOWCPFCwG8skJS2mCdWoo0GzlCw4xcTi/AAN+c662E2+v1s55iVxkyplPDRnf1/GzeZN9tRMaqBIeUxxsu8vZTjJX+lFrG1R5VdbBZtAp5T6vsmZNxj7cDMqLI5IYqF+amRsYyooYoLCwnnknJ7B8eIXCAEopjOmso3x3LPYLrmxJI00DZ7iyUc+RFiu1zj9YXCQkyWyAR+T4GFd4fIvwz9bqKcMdSI9ZC3VJ7XzW3hsnUezFcm7zx9SgOi0r4lT7zBsOE+Ed3e5LogXRXQ1o5tBzbK9LmolfS+bGZ5szhFIuYYISHntm6mPGsCRZggSTHOyMRdUztd98e7uLD1Ux8XkhzRIREAjSMMpj+7K++pBe81VB1NMzfdErR3MN1eecwpC5spQk0l4AqyqM9UY18g0sIpNwY74Z5i236SpsXmSuM9y6C3g==
    username: AgAxbBHqwvnK4nz1E3k+IAThYV/Nz/h3tHQxO/A5MMMzRxUyrU3bSnVpr65umilBtLj94BlM5uwvnVImlRbEi4xSk/5AZXLDFGtqGdTV08wB0NtBeETUM4RF951zihW1W+R8+DJI6iVwbYNobPlFIHgOgoTmZtkaZNVPIO35JN9RmI3sdRRkTqfc+Dn+dFZh47HM+NEqE/cTUlzoIB60emH3sqLrAwLRBbBGiBXRFpvXMWMzfcjj/4QzTqkHsUPc6ne1nT1riNOAsVlntUy5cps10B9TB8oynQOtcSR33QeitkGyJWTluS1S2Bth8aOKROdhgeioGGJkEezAAKq9N6PtG5GmxnnDeDGu6VfDf0NMQeZKqpXYatE5RSi7Pr6QutW4onXcLxKacoTNpWIyjOQTAp3nIaUq0mI88vH6JIkJs5n0qXkhWv/98oTK1mPh/NRaOQJvgMG4pRQta/32epL2juzUZq253FYZSf7ivOgMT1U6b7jH3AIBRWMAYQNBAsXDSNs/Q9hAqJwFBBnDYlzIuyeOExVZAuQyiOqGXgxy5O2fe+jaDNc72+IfWhwulZcYUtiNr0wrPAHzL4T54anbuCwcwL3MB/zcn69etb102I4Hvn/tgcIZjSds7ji6vWMNMB1bRThyfceluGemFHEAIVfeVcQ11KA27bJ8v+O2sVaig6ChRsm8w8iPPM4lEBx+bvwU4A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-admin-credentials
