---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gpustack
  namespace: gpustack-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/gpustack/gpustack-chart
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "2.2.3"
