---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  enableSuperuserAccess: true
  instances: 1
  storage:
    size: 20Gi
  managed:
    roles:
    - name: airflow
      login: true
      passwordSecret:
        name: airflow-basic-auth
