---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-rw-pooler
  namespace: cnpg-system
spec:
  cluster:
    name: postgres
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
      server_lifetime: "300"
      server_idle_timeout: "120"
