---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mistershell-secrets
  namespace: mistershell
spec:
  encryptedData:
    db-encryption-key: AgBkH46+ERk+PrqdAHUnIq+/aQe6eYI+xXQZmkg5imwkJHfscScl/R/6ZErZmUHl3nw5oyI0nzyhkmgMEWXC0RliZG79o8XfL+50A4uhug+BH+xQHxXnqNVlFrJiPfNhAPvN/ugAWFnz099fqgim9iJy/99n+b1M5NidRPpuk9/QZowbJJGKm6PTMNDoegiKE2PrrPv31OJy8+Bhb7dgdojXIow6WnFdDDpzUfEjxUHQuBNzmxSlJaZxPVpVDbUvYSFLa3B1W4FY1eRx6Rs1CPy7FGLPvVAD+eKp6oEixJ5ffpXumV1NIUqoSrf487ODq7MKYRxkfxUnN/vMYUEK4w+ArcZ/ja8MzYfTErCsqxr5L9UREyLD4iraPs3I81XkKokHwM0EQrolloZC90QtG/XXWXLz93/VshqV8cFj2G2iClDKKxhfHFugMJvs+8vbQVWS43rVWIV2uNZn/ILA7J/Fhm1v06RpV+j64GoLGzsG/0gnLJMkB+o7bV+qKs5jlTJIO5WRyBi3WJVmoyyQnXDtTadVq2QK8G/IfY54X+ECz9VDYl9WCccB0ZpTV512CxQAiBpPsUhisxKnLBOCYWNd6EsxHl0bixIrKpWEyUIUfnw+MEthfxqZUDTLx32fzLs/VvNgc1ZDT3rgxItINxu+POu/Wi3GHixDRvNxNaIjj87I9yC+7HI5Tzjz34heMfez+4NrmTrzHQYO+7eRCw/DEiimNUC8QW7752feZxYvZW4XshxG4JPL0EscS2mFuMZIwctw8iPsnASbWjMcAdLF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mistershell-secrets
      namespace: mistershell
