---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-fernet-key
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-fernet-key
  data:
    - secretKey: fernet-key
      remoteRef:
        key: airflow/fernet-key
        property: fernet-key
