---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy-cookie
  namespace: oauth2-proxy
spec:
  encryptedData:
    cookie-secret: AgBYVFC81WlYD3hsPbpW34tU8oHxtwFhTbsDEQvve6NA8kkKaAIrOFgZBzeTWzpN1iqUG4CWjQk56Elm1VIq4fVOBogh5EAJQ36KKMN1EwqKAz6EICrA7/Q3mWMd1X5U75b4aKGpmpRZq74IX+B8YK/E9En1Jkl13ZyptX1zIdl0OFQcDBoaXQ/Ul3yhsYKlmXMfZ0cHw4bV/h6D3dhSmICMoDLXpRBybjnXibVIF0eQPq/h1CB4OgoEIGRG8qk5JkqWaMFEZZJmo7kKRlVvTCAbpj6FuSrolSzfImo0IuG/ONzrGseEudAU3ZH8Tv0UmqYXAFNIWPXt7rHIdldUqO2MAFdns2RU1dLylp8fQQ49eszDV4bx6qs2XawdtdpIBHCvqia67Lb4PHNMM02mjMllHsrcQmqrGuGs9TMuzq6Q0GBb38X+LCwnxflJpK98xAlhNo7rrf29FLAgJIeRTt2sokgi8DCGP9dCodIl0rIoazTKf2wuxtRnGVzZbUXlPF0wkJBSRBKysX44ZOH3qEwSqg0MAPd80ucX/ekf+ZESNvrR2uIOw1vM/r8m1jO+BDx9UzF/OsEqvgWJs3Jt5dHCB2+LSgFBP5b09+ibmqI0dRy/K4pDKnBhOgjjro9xd+ZxPdDazQ+xMYG015CA0jM/2Ck66d8fOnjT0kgTGYAoLXU1E1O5xi/FWJ37s7czTGPvndSKmHr0uBySox0VuMDlvtEjRxrZ7ItoZ9sFwz3rdrBw8pDdPGH+CXjUiQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oauth2-proxy-cookie
      namespace: oauth2-proxy
