---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: filestash
  namespace: filestash
spec:
  interval: 10m
  chart: filestash
  version: "4.0.0"
  sourceRef:
    name: filestash
    kind: HelmRepository
