---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  interval: 10m
  chart: cloudbeaver
  version: "1.1.5"
  sourceRef:
    name: avisto
    kind: HelmRepository
