---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: cloudbeaver
    namespace: cloudbeaver
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: cloudbeaver.${domain}
      tls: true
