---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 10m
  url: oci://registry-1.docker.io/cloudpirates/keycloak
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "0.21.10"
