---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: airflow
  namespace: ${namespace}
spec:
  inputs:
    - service: "airflow-tls"
      path: "./secrets/base/shubhamtatvamasi-tls"
      tls_secret_name: "airflow-tls"
    - service: "git-credentials"
      path: "./secrets/git-credentials"
    - service: "airflow-metadata-connection"
      path: "./secrets/airflow/airflow-metadata-connection"
    - service: "airflow-config"
      path: "./deployments/${namespace}"
    - service: "airflow"
      path: "./workloads/airflow/airflow"
      dependsOn:
        - "postgres"
        - "airflow-tls"
        - "git-credentials"
        - "airflow-config"
        - "airflow-metadata-connection"
      workers_replicas: "${workers_replicas}"
      dags_git_sync_enabled: "${dags_git_sync_enabled}"
      dags_git_repo: "${dags_git_repo}"
      dags_git_branch: "${dags_git_branch}"
      dags_git_subpath: "${dags_git_subpath}"
  resourcesTemplate: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.service >>
      namespace: ${namespace}
    spec:
      interval: 10m0s
      path: << inputs.path >>
      prune: true
      wait: true
      timeout: 10m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

      <<- if index inputs "dependsOn" >>
      dependsOn:
        <<- range index inputs "dependsOn" >>
        - name: << . >>
        <<- end >>
      <<- end >>

      postBuild:
        substitute:
          namespace: ${namespace}

          <<- if index inputs "tls_secret_name" >>
          tls_secret_name: "<< index inputs "tls_secret_name" >>"
          <<- end >>

          <<- if index inputs "workers_replicas" >>
          workers_replicas: "<< index inputs "workers_replicas" >>"
          <<- end >>

          <<- if index inputs "dags_git_sync_enabled" >>
          dags_git_sync_enabled: "<< index inputs "dags_git_sync_enabled" >>"
          <<- else >>
          dags_git_sync_enabled: "false"
          <<- end >>

          <<- if index inputs "dags_git_repo" >>
          dags_git_repo: "<< index inputs "dags_git_repo" >>"
          <<- end >>

          <<- if index inputs "dags_git_branch" >>
          dags_git_branch: "<< index inputs "dags_git_branch" >>"
          <<- end >>

          <<- if index inputs "dags_git_subpath" >>
          dags_git_subpath: "<< index inputs "dags_git_subpath" >>"
          <<- end >>
