---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: rancher
    namespace: cattle-system
  values:
    hostname: rancher.k8s.shubhamtatvamasi.com
    bootstrapPassword: admin
    ingress:
      ingressClassName: traefik
      tls:
        source: secret
        secretName: rancher-tls
    replicas: 1
