---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-connections
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: airflow-connections
  data:
    - secretKey: AIRFLOW_CONN_MY_HARBOR
      remoteRef:
        key: airflow/connections
        property: AIRFLOW_CONN_MY_HARBOR
    - secretKey: AIRFLOW_CONN_MY_POSTGRES
      remoteRef:
        key: airflow/connections
        property: AIRFLOW_CONN_MY_POSTGRES
    - secretKey: AIRFLOW_CONN_MY_VM
      remoteRef:
        key: airflow/connections
        property: AIRFLOW_CONN_MY_VM
