---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: factorio
  labels:
    app: factorio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      securityContext:
        fsGroup: 845
      containers:
      - name: factorio
        image: factoriotools/factorio:latest
        env:
        - name: GENERATE_NEW_SAVE
          value: "true"
        ports:
        - name: game
          containerPort: 34197
          protocol: UDP
        - name: rcon
          containerPort: 27015
          protocol: TCP
        volumeMounts:
        - name: factorio-data
          mountPath: /factorio
        securityContext:
          runAsUser: 845
          runAsGroup: 845
      volumes:
      - name: factorio-data
        persistentVolumeClaim:
          claimName: factorio-data
