---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: monitoring
  values:
    prometheus:
      # service:
      #   type: LoadBalancer
      prometheusSpec:
        serviceMonitorNamespaceSelector:
          matchLabels:
            monitoring: enabled
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.k8s.shubhamtatvamasi.com
        tls:
          - secretName: kube-prometheus-stack-tls
            hosts:
              - prometheus.k8s.shubhamtatvamasi.com
    grafana:
      # service:
      #   type: LoadBalancer
      adminUser: admin
      adminPassword: admin
      # Logs Drilldown app (Metrics/Traces/Profiles Drilldown ship by default).
      plugins:
        - grafana-lokiexplore-app
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.k8s.shubhamtatvamasi.com
        tls:
          - secretName: kube-prometheus-stack-tls
            hosts:
              - grafana.k8s.shubhamtatvamasi.com
