---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-run
  namespace: portainer-run
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: portainer-run
    namespace: portainer-run
  values:
    dnsConfig:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: portainer-run.${domain}
          paths:
            - path: /
      tls:
        - secretName: portainer-run-tls
          hosts:
            - portainer-run.${domain}
    service:
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: "https"
        traefik.ingress.kubernetes.io/service.serverstransport: "portainer-run-portainer-run@kubernetescrd"
