---
apiVersion: v1
kind: Secret
metadata:
  name: portainer-run-secret
  namespace: portainer-run
type: Opaque
stringData:
  ENCRYPTION_KEY: "7bceb47a40e30e4c527995e602015ebae0ffa94c4efd80187d0c684d30b7ddf8"
  ANTHROPIC_API_KEY: ""
