---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitwarden-db-auth
  namespace: bitwarden
spec:
  encryptedData:
    password: AgBaiGG0d4pc/mhP2mFvj/RcxmMVwkosq4JXX1/sqJD5LnMMyMWPdbu27COU5M4w/FK/qA9W+l1yR5qfOeQTNprG2bbnfp7fxGXd47tD03n7avZE9MFPisglNiSjWXs0lF0NRUoDrimjWsfG51CBhNZdJF1NlbifiWxIPyRv9l2yBQipruCnrUbeTRWOSgf+MbwdsX1xJd0R5xz3UyGSFrJGHf7/PRfq7i4ppu8RJEFZhHcRli05t2WQzD0OL8FtwEfmkDh3CGv0xG1g59qQaK2cBCFwcn0P1fIgIov0yTSW3AJXuFspuRO1akJCrq43K6JCsDjrTLbxMLnT1Hk5WWopW9YdoeNWQrQq9Nf+9AeYQ2Pmi0TalgShnJvxgcB05O975FuOVoKbCBEatpzIlnwmLY8qD0Gll7eBTfXdexggRQGjXH6g+TqoEtKK6wg6xHo3kGdP5I2x1lBslpvw0jX2AHFhs6yG97TLJpffxDVUSN53S16C3p4DqD7TJkEsqtKzeXk1Dbm5s8DprHU+KbOZrhFWbgXPzdYzkSjF8ruIzq3EDKVeXz2yQ9wDaX/y7MwAur7hHhIiR2OCGjffjOy7nFHa1zfRojXtGNhLni+f82ChM7PgWpZVhYZKprMAVd3byXxR+uMZkeqyavx486phKHsSMswUxqY1JF/zvusRrmTjo8qVgimoIgb2UdzF2k2ABUO3x71xAJLxbq4sTiDXkGS71+pgyYqvcHQlbsZiig==
    username: AgAocGla9fU15j5TXqu+BQBCp5UeknKvdFK442m4RI+XZfGF5+739HFKgvLtq7htPO1LEWpHdJTO9z/dLI0L/Y/nV5vyU8n/iHc33E099zHLyWQSYcXJhzkM7OdPb9w+ow1EIdYa+tPC+XvKAsGjff0cHhxLR+DM5OWhA6Nh/feWjkH0BIr7WRKNbNEeruWpsB9sBPgsIGo7jwp9wzhv0DYVF7hgK7JWBZvhrRJkgDvkeUZTMl1JJ9qDIR8MK6w7szsXTt3LYhG+U4WtmJyU+n1f/gNVNCyTSK4g6fcAr7zore28Dnl05j6vSWeeKfLjE3ti6qtKumtTy7LDnqw2Ynne4Zj6iX7HTE5+6CVjSc6icnwreQSCsh7ZUitTXQYRyTX1t8ELv0hIthPhGt1PI7PUcAVuehw7hEdIdgd+F93cz3tL9vWiyj/7GWyZ2NtG8pDVsqTxRWFej0rywrJe8XvuWdBvvgTgVWFiyFCFli6GIRCtEuX64rLdKPOMfFDHtzkEjrZbRZnB2VO2AIhbYnW+wK7v19NIpgtfuXg3atn7HRZcPIZnb1FNYsOTSpokYIUDMQISAgUUbRhP6E/CT9FRUDGaGZ/iOEe56vCKt0wp+KlTRrCHbVm0XEZIEixDEEsUGKp1XMQJWbYaPs1iljfGAXn9xc5yAkIT9ogukb8/uOlr39dnM0IqxcMaOS8dILNwPzccHyoIIYQ=
  template:
    metadata:
      name: bitwarden-db-auth
      namespace: bitwarden
    type: kubernetes.io/basic-auth
