---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden-postgres
  namespace: bitwarden
spec:
  interval: 10m0s
  path: ./infrastructure/base/postgres
  postBuild:
    substitute:
      namespace: bitwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: true
