---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "6.0.6"
