---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart: vault
  version: "0.34.0"
  sourceRef:
    name: hashicorp
    kind: HelmRepository
