---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: airflow
    namespace: airflow
  values:
    airflowVersion: "3.2.0"
    defaultAirflowTag: "3.2.0"
    executor: "CeleryExecutor"
    postgresql:
      enabled: false
    apiServer:
      service:
        type: LoadBalancer
    migrateDatabaseJob:
      useHelmHooks: false
    createUserJob:
      useHelmHooks: false
    data:
      metadataConnection:
        host: postgres
