---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: airflow
    namespace: airflow
  install:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  values:
    airflowVersion: "3.2.0"
    defaultAirflowTag: "3.2.0"
    executor: "CeleryExecutor"
    postgresql:
      enabled: false
    apiServer:
      service:
        type: LoadBalancer
    data:
      metadataConnection:
        user: postgres
        pass: postgres
        protocol: postgresql
        host: postgres
        port: 5432
        db: postgres
        sslmode: disable
