---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: ${namespace}
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: airflow
    namespace: ${namespace}
  install:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  values:
    airflowVersion: "3.2.0"
    defaultAirflowTag: "3.2.0"
    executor: "KubernetesExecutor"
    postgresql:
      enabled: false
    opensearch:
      enabled: true
      connection:
        scheme: https
        user: "admin"
        pass: "StrongPassword123!"
        host: "opensearch-cluster-master.opensearch"
        port: 9200
    # ports:
    #   apiServer: 80
    #   airflowUI: 80
    apiServer:
      service:
        type: LoadBalancer
    migrateDatabaseJob:
      useHelmHooks: false
    createUserJob:
      useHelmHooks: false
    workers:
      replicas: ${workers_replicas}
    data:
      metadataConnection:
        host: postgres
    images:
      gitSync:
        tag: v4.6.0
    dags:
      gitSync:
        enabled: ${dags_git_sync_enabled}
        credentialsSecret: git-credentials
        repo: ${dags_git_repo}
        branch: ${dags_git_branch}
        ref: ${dags_git_branch}
        subPath: ${dags_git_subpath}
