---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-variables-import
  namespace: ${namespace}
data:
  variables.yaml: |
    MY_RKE_AIRFLOW:
      description: My RKE Airflow
      value: airflow-rke2-one
    MY_NEW_RKE_AIRFLOW:
      description: My New RKE Airflow
      value: airflow-rke2-two
