---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  chart: rook-ceph
  version: "v1.20.7"
  sourceRef:
    name: rook-ceph
    kind: HelmRepository
