---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: git-credentials
  data:
    - secretKey: GIT_SYNC_PASSWORD
      remoteRef:
        key: airflow/git-credentials
        property: GIT_SYNC_PASSWORD
    - secretKey: GIT_SYNC_USERNAME
      remoteRef:
        key: airflow/git-credentials
        property: GIT_SYNC_USERNAME
    - secretKey: GITSYNC_PASSWORD
      remoteRef:
        key: airflow/git-credentials
        property: GITSYNC_PASSWORD
    - secretKey: GITSYNC_USERNAME
      remoteRef:
        key: airflow/git-credentials
        property: GITSYNC_USERNAME
