---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  interval: 10m
  chart: nginx-gateway-fabric
  version: "2.5.x"
  sourceRef:
    name: nginx-gateway
    kind: OCIRepository
