---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: nginx-gateway
    namespace: nginx-gateway
