---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: ${namespace}
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: airflow
    namespace: ${namespace}
  install:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
    disableWait: false
  values:
    airflowVersion: "3.2.1"
    # defaultAirflowTag: "3.2.1"
    defaultAirflowTag: "3.2.1-2"
    defaultAirflowRepository: "shubhamtatvamasi/airflow"
    executor: "KubernetesExecutor"
    postgresql:
      enabled: false
    opensearch:
      enabled: true
      connection:
        scheme: http
        host: "opensearch-cluster-master.opensearch"
        port: 9200
        # user: "admin"
        # pass: "StrongPassword123!"
    config:
      webserver:
        expose_config: 'True'
        update_fab_perms: 'True'
      logging:
        delete_local_logs: 'False'
      opensearch:
        host: "http://opensearch-cluster-master.opensearch"
        port: 9200
        write_to_os: 'True'
        json_format: 'True'
        write_stdout: 'False'
      opensearch_configs:
        use_ssl: 'False'
        verify_certs: 'False'
        ssl_assert_hostname: 'False'
      elasticsearch: ~
      elasticsearch_configs: ~
      # elasticsearch:
      #   host: "http://opensearch-cluster-master.opensearch:9200"
      #   log_id_template: "{dag_id}_{task_id}_{run_id}_{try_number}"
      #   json_format: 'True'
      #   verify_certs: 'False'
      # elasticsearch_configs:
      #   use_ssl: 'False'
      #   verify_certs: 'False'
    # extraEnv: |
    #   - name: AIRFLOW__OPENSEARCH__PORT
    #     value: '9200'
    # ports:
    #   apiServer: 80
    #   airflowUI: 80
    # apiServer:
    #   service:
    #     type: LoadBalancer
    migrateDatabaseJob:
      useHelmHooks: false
    createUserJob:
      useHelmHooks: false
    workers:
      replicas: ${workers_replicas}
    data:
      metadataConnection:
        host: postgres
    images:
      gitSync:
        tag: v4.6.0
    extraEnvFrom: |
      - secretRef:
          name: 'airflow-connections'
      - configMapRef:
          name: 'airflow-variables'
    dags:
      gitSync:
        enabled: ${dags_git_sync_enabled}
        credentialsSecret: git-credentials
        repo: ${dags_git_repo}
        branch: ${dags_git_branch}
        ref: ${dags_git_branch}
        subPath: ${dags_git_subpath}
    ingress:
      web:
        enabled: true
        hosts:
          - name: airflow.k8s.shubhamtatvamasi.com
            tls:
              enabled: true
              secretName: shubhamtatvamasi-tls
        tls:
          enabled: true
          secretName: shubhamtatvamasi-tls
