---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
  namespace: rook-ceph
spec:
  interval: 10m
  chartRef:
    kind: HelmChart
    name: ceph-csi-drivers
    namespace: rook-ceph
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        nodePlugin:
          priorityClassName: system-node-critical
        controllerPlugin:
          priorityClassName: system-cluster-critical
    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        enableFencing: true
        deployCsiAddons: true
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
      nfs:
        enabled: true
        name: rook-ceph.nfs.csi.ceph.com
      nvmeof:
        enabled: true
        name: rook-ceph.nvmeof.csi.ceph.com
