---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  inputs:
    # controllers
    - service: "metallb"
      path: "./infrastructure/base/metallb"
    - service: "openebs"
      path: "./infrastructure/base/openebs"
    - service: "sealed-secrets"
      path: "./infrastructure/base/sealed-secrets"
    - service: "reloader"
      path: "./infrastructure/base/reloader"

    # flux web UI TLS (sealed secret decrypted by sealed-secrets)
    - service: "flux-tls"
      path: "./secrets/base/shubhamtatvamasi-tls"
      tls_secret_name: "flux-tls"
      namespace: "flux-system"
      dependsOn:
        - "sealed-secrets"

    # metallb config (needs the metallb controller CRDs first)
    - service: "metallb-config"
      path: "./infrastructure/rke2/metallb-system"
      dependsOn:
        - "metallb"

    # network and ingress
    - service: "gateway-api"
      path: "./infrastructure/base/gateway-api"
    - service: "traefik"
      path: "./infrastructure/base/traefik"
      dependsOn:
        - "metallb-config"
        - "sealed-secrets"
        - "gateway-api"

    # applications
    - service: "harbor"
      path: "./infrastructure/base/harbor"
      dependsOn:
        - "traefik"
        - "openebs"
        - "sealed-secrets"
    - service: "dex"
      path: "./infrastructure/base/dex"
      dependsOn:
        - "traefik"
        - "sealed-secrets"
    - service: "oauth2-proxy"
      path: "./infrastructure/base/oauth2-proxy"
      dependsOn:
        - "dex"
    - service: "portainer"
      path: "./infrastructure/base/portainer"
      dependsOn:
        - "traefik"
        - "openebs"
        - "sealed-secrets"
    - service: "kube-prometheus-stack"
      path: "./infrastructure/base/kube-prometheus-stack"
      dependsOn:
        - "traefik"
        - "openebs"
        - "sealed-secrets"

    # Gitea
    # - service: "gitea"
    #   path: "./infrastructure/base/gitea"
    #   dependsOn:
    #     - "traefik"
    #     - "openebs"
    #     - "sealed-secrets"

    # Research
    - service: "keycloak"
      path: "./infrastructure/base/keycloak"
      dependsOn:
        - "traefik"
        - "sealed-secrets"
  resourcesTemplate: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.service >>
      namespace: flux-system
    spec:
      interval: 10m0s
      path: << inputs.path >>
      prune: true
      wait: true
      timeout: 10m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

      <<- if index inputs "dependsOn" >>
      dependsOn:
        <<- range index inputs "dependsOn" >>
        - name: << . >>
        <<- end >>
      <<- end >>

      <<- if index inputs "tls_secret_name" >>
      postBuild:
        substitute:
          tls_secret_name: "<< index inputs "tls_secret_name" >>"
          namespace: "<< index inputs "namespace" >>"
      <<- end >>
