---
# internal fixed-name ClusterIP Service; LiteLLM calls http://kserve-ingress-gateway.envoy-gateway-system.svc/v1
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: kserve-ingress-gateway
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: kserve-ingress-gateway
        type: ClusterIP
