---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gatewayclass.yaml
- envoyproxy.yaml
- gateway.yaml
- securitypolicy.yaml
- podmonitor.yaml
- kserve-api-keys.yaml
- ingress.yaml
- kserve-ingress-gateway-tls.yaml
